# ─── Node box ────────────────────────────────────────────────────────────────
[box-01]
image=ubuntu:25.10
pull=true
root=false
replace=false
init=false
start_now=false
home=~/.distrobox/box-01
volume=/data:/data
additional_packages=git curl wget build-essential ca-certificates unzip
# init_hooks=curl https://mise.run | sh; ~/.local/bin/mise use --global node@lts; echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc

# ─── Rust box ────────────────────────────────────────────────────────────────
# [ubuntu-rust]
# image=ubuntu:25.10
# pull=true
# root=false
# replace=false
# init=false
# start_now=false
# volume=/data:/data
# additional_packages=git curl wget build-essential pkg-config ca-certificates unzip
# init_hooks=curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path; echo 'source "$HOME/.cargo/env"' >> ~/.bashrc

